apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-world-service
spec:
  selector:
    app: springboot-hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
